---
title: "Project Proposal"
author: "Group 6: Wenyu, Mason, Justina, Stella, Bahiravi"
---


## Data Preview

```{r}
df = read.csv("friday2017_sample.csv", header = TRUE)

# Display only the first 10 columns
df_subset <- df[, 1:10]

# Print the first few rows of the selected columns
head(df_subset)
```


## Data Source
* https://www.kaggle.com/datasets/ernie55ernie/improved-cicids2017-and-csecicids2018/data
* The dataset contains millions of internet traffic logs of normal activities and intrusions. Our goal is to predict the type of internet activities using various packet metadata as predictors.



## Variable Description
* Id: An ID that is assigned for each flow in the dataset
* Flow Id: A unique ID for each flow of data
* Src IP: The source IP address involved in the data flow
* Src port: The source port number used in the communication
* Dst IP: The destination IP address in the flow
* Dst Port: The destination port number for the communication
* Protocol: The communication protocol used
* Timestamp: The time the flow data was recorded
* Flow Duration: The duration of the flow in seconds
* Total Fwd Packet: The total number of forward packets in the flow
* Et al.


## Statistical Methods
* Logistic Regression
* Lasso Regularization
* ANOVA and Visualization


## Computational steps
* Clean the dataset and split it into smaller sets.
* Fit Logistic regression on each set to predict the label (intrusion or benign).
* Average the coefficients from each set to build a general model.
* Test accuracy and compare features with Lasso.


## GitHub Repo
* https://github.com/wdai405/STAT405_Final_Project

